development:
  adapter: postgresql
  encoding: unicode
  database: serviceX_development
  pool: 5
  username: pixelbytes
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: serviceX_test
  pool: 5
  username: pguser
  password: nabeel

production:
  database: ENV['DATABASE_URL']